### PR TITLE
Bringing Sprint 3 work into master

### PR DESCRIPTION
**Pull request by trevorforrey**
Bringing sprint 3 work into master

### CODE REVIEW

**Review by jdbecke3 — APPROVED** [review]
Plug In: opens the file (program) correctly –  Style looks more like java then cpp, but overall look good. Does not adhere to Object Oriented Principles . With the use of global and did not declare an instance of a global variable.  Only works and tested on Windows 7 or Windows 10. Needs write privileges to work.  Warring Does not catch any exceptions or errors.

Issue Calendar not showing up – needed to delete code that had to do with old small calendar frame, code looks good and tested.

Calendar task information –  dialog box adheres to standards that have been used in the past. Looks effective and well done.  Within JNCalendarCellRenderer  sort of redundant when instantiating it  using of mod and even numbers. Need to repaint after closing the dialog box.

Code for fixing the new Task Creation inside the menu bar -  works as expected looks like the code adheres to the other code that has been implemented at a later time.

**Review by lilianngweta — APPROVED** [review]
-Nice work on implementing that Notepad plugin even though it only works on Windows OS
-Good job on fixing the calendar bug because it was really affecting us.
-Awesome job making that idle notifier work, but your try catch block is missing the finally block. Also, nice javadoc for your code.
-I am impressed by everybody's work. Good job team!

**Comment by trevorforrey** [comment]
**Jake - ** PluginDefinition.cpp - File name variable is not initialized. Plugin only works on Windows operating systems. (only tested on windows 7 and 10). Exception handling is not incorporated into implementation.
**Lilian - ** Code is styled well and functionality works.
**Josh - ** Code is very well commented and styled. Having the timer reset after every paint() is overhead.
**Alec - ** Commented out debugging code is still present (I'm also victim to this). 
image uploaded from ios 1

**Review by jwleona2 — APPROVED** [review]
- Need more use of try/catch blocks

- Global Var usage not necessarily adhering to OOP

- Closing file input stream 

- JNCalendarRenderer - Event instantiation uses odd method of filtering out values by even numbers only.

- Dialog Box Remnants of the panel event. In future, call repaint

- Cyclomatic complexity of some methods high. For example, While-->if-->switch --->

- Could use more comments in certain areas.

Otherwise from nitpicking these points, the code seems functional!

**Review by atshinn — APPROVED** [review]
Jakes code looked good but no exceptions and styling as a little off
Trevors code was great had excellent commentation
Joshs code made good use of several design patterns that made the code much easier to read.
Lillians code was straightforward and looked good.

**Comment by trevorforrey** [comment]
Ok, Great! Everything is definitely good now!

**Pull request merged**
