### PR TITLE
Issue 149 Fix

### PR DESCRIPTION
**Pull request by trevorforrey**
Edit task now populates the window with the task information. Also, "actual" fields have been created inside the task creation window.

### CODE REVIEW

**Review by jwleona2 — CHANGES_REQUESTED** [review]
Trevor and I discussed the following concerns over an informal code-review during a screencast session. Some issues I had with attempting to run:

- Cannot create a new task (Unresponsive)

- There are potential XML parsing issues (maybe problem with system-level encoding: ANSI, UTF, UNICODE, etc.) with how quotes " are read

- Input validation non-functional

- GUI Layout needs addressed at some point (maybe in another task)

**Comment by trevorforrey** [comment]
Hi Jake. Thanks for pointing out the points above during our code review. These are serious issues that will need to be addressed after completion of issue #149. I have fixed the issue where new task creation was not working correctly. Please test and let me know if it works on your end.

**Review by jwleona2 — COMMENTED** [review]
Hey Trevor!

Looks pretty darn good! I approve the pull-request and you may pull changes to Development if you wish. 

I did find some odd bugs that aren't necessarily related to your implementation, but I'll let you use your discretion on whether to address that here or elsewhere. 

- Tasks added from "New Task" on menu bar do not populate, but when the New Task icon is selected within the task panel, it works fine.

- Sometimes when pressing submit without changing default values, the "New Task" icon under the task panel gets grayed out and you cannot create any new tasks without restarting Memoranda.

**Comment by trevorforrey** [comment]
Hi Jake, Thanks for reviewing. You brought up a lot of important errors. I'll set those up as Issues and Create Tasks for them in Taiga.

**Pull request merged**
