### PR TITLE
Bringing in development into master - End of Sprint 2

### PR DESCRIPTION
**Pull request by trevorforrey**
Bringing in the working development code into master. End of Sprint 2.

### CODE REVIEW

**Review by atshinn — APPROVED** [review]
Should ve created an interface so that all our gui code is organized into the same methods.

**Review by jdbecke3 — APPROVED** [review]
Calendar: create singleton nice work. code standards are good. organized class well and functionality is working.
missing JavaDoc in all classes that implement Calendar. also there is a lot of commented code that could be deleted.
overall Calendar functionality works as expected, and is written well and is easy to follow, in the future would suggest writing more documentation and adhere to code standers. 

Timer: javaDoc looks good, a bit confusing to follow variables meanings. but structured well

Task Window: code looks good missing java doc, but very well commented for readability. looks good.

**Review by jwleona2 — APPROVED** [review]
###Calendar Functionality###

Some of the member variables do not have private/protected keywords associated, leaving in the default state. 

TaskSearchPanel.java

Some code not utilized. For example, 202. 

Little to no javaDoc


### TaskBoard ###

Most if not all javaDoc implemented, very nice!
Lots of line spacing

Could use a filler or invisible box as opposed to empty JLabel, though I'm not sure what's more conventional



Overall great! These are just general comments jotted down as we were discussing during the code-review session. To note, I am also guilty of these code quality concerns. Overall, looks pretty good!

**Review by lilianngweta — APPROVED** [review]
-The calendar task search and the back and forward button implementations look great!

-The timer implementation code looks good.

-Overall I like the changes that have been made. Great job team!

**Comment by trevorforrey** [comment]
Looks beautiful ;') So proud of us

**Pull request merged**
